# Generated by Django 6.0.4 on 2026-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=100)),
                ('genre', models.TextField(max_length=100)),
                ('publication', models.DateField()),
            ],
        ),
    ]
