# Generated by Django 6.0.4 on 2026-04-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_publication_book_first_published_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
